### ISSUE TITLE
Wireless Door and Glass Break Sensor not supported 

### ISSUE THREAD

**Issue by 007GTCS** [balansse/homebridge-vivint#10]
My Vivint door and glass brake sensor seem to not be supported. Below is the log snippet and attached is my log.

[37m[10/13/2020, 2:12:09 PM] [39m[36m[Vivint] [39mDevice not (yet) supported [ID]:21 [Type]:wireless_sensor [EquipmentCode]:863 [Name]:Back Door
[37m[10/13/2020, 2:12:09 PM] [39m[36m[Vivint] [39mDevice not (yet) supported [ID]:26 [Type]:wireless_sensor [EquipmentCode]:864 [Name]:Garage Glass Break
[37m[10/13/2020, 2:12:09 PM] [39m[36m[Vivint] [39mDevice not (yet) supported [ID]:27 [Type]:wireless_sensor [EquipmentCode]:864 [Name]:Kitchen Glass Break

**Comment by balansse** [comment]
Added in 1.3.0
