### ISSUE TITLE
Seeing same error as stated before with latest version on HOOBS

### ISSUE THREAD

**Issue by jpop77** [balansse/homebridge-vivint#11]
Just uploaded the latest vivint package into HOOBS and this continues to kill the bridge with the following errors:

10/21/2020, 12:34:49 AM Error loading platform requested in your config.json at position 2
10/21/2020, 12:34:49 AM Error: The requested platform 'Vivint' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:342:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:328:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:92:35)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:87:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

Let me know if I am missing something.  I tried earlier versions to have them all fail.  Running this on the latest mac OS edition.

**Comment by balansse** [comment]
Could you please check what is in the log file before the 'The requested platform 'Vivint' was not registered by any plugin.' error? There might be an issue with your node.js version

**Comment by closeshave2** [comment]
I just update HOOBS to v3.2.7 this morning.  I'm getting the same error.  Here's everything from the log file:

10/21/2020, 7:41:07 AM Loaded config.json with 0 accessories and 5 platforms.
10/21/2020, 7:41:07 AM ---
10/21/2020, 7:41:07 AM Loaded plugin: homebridge-camera-ffmpeg@3.0.3
10/21/2020, 7:41:07 AM Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
10/21/2020, 7:41:07 AM ---
10/21/2020, 7:41:08 AM Loaded plugin: homebridge-harmony@1.4.0
10/21/2020, 7:41:08 AM Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
10/21/2020, 7:41:08 AM ---
10/21/2020, 7:41:08 AM Loaded plugin: homebridge-ring@9.9.0
10/21/2020, 7:41:08 AM Registering platform 'homebridge-ring.Ring'
10/21/2020, 7:41:08 AM ---
10/21/2020, 7:41:08 AM Loading 5 platforms...
10/21/2020, 7:41:08 AM [Ring] Initializing Ring platform...
10/21/2020, 7:41:08 AM Error loading platform requested in your config.json at position 2
10/21/2020, 7:41:08 AM Error: The requested platform 'Vivint' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:342:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:328:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:92:35)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:87:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
10/21/2020, 7:41:08 AM Got SIGTERM, shutting down Bridge...

**Comment by closeshave2** [comment]
For what it's worth, I'm on Node.js v12.16.3.

**Comment by balansse** [comment]
Unfortunately, this log file is not telling me much as it does not show why the platform is not loading.
I remember other people that had issues with HOOBS were ok when they restarted the system completely. Have you tried full restart?

**Comment by jpop77** [comment]
Here are the additional logs, which show the safe failure around a missing accessories:

10/20/2020, 11:55:00 PM  WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
10/20/2020, 11:55:04 PM npm
10/20/2020, 11:55:04 PM  WARN react-native-securerandom@0.1.1 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
10/20/2020, 11:55:04 PM npm
10/20/2020, 11:55:04 PM WARN @unimodules/react-native-adapter@5.6.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
10/20/2020, 11:55:04 PM npm
10/20/2020, 11:55:04 PM WARN @unimodules/react-native-adapter@5.6.0 requires a peer of react-native-web@~0.13.7 but none is installed. You must install peer dependencies yourself.
10/20/2020, 11:55:04 PM 
10/20/2020, 11:55:04 PM + @balansse/homebridge-vivint@1.3.1
added 102 packages from 99 contributors in 5.323s
10/20/2020, 11:55:04 PM 
17 packages are looking for funding
  run `npm fund` for details
10/20/2020, 11:55:04 PM 
┌──────────────────────────────────────────────────────────────────┐
│                     npm update check failed                      │
│               Try running with sudo or get access                │
│               to the local update config store via               │
│ sudo chown -R $USER:$(id -gn $USER) /Users/lauriejackson/.config │
└──────────────────────────────────────────────────────────────────┘
10/20/2020, 11:55:04 PM Plugin "@balansse/homebridge-vivint" installed.
10/20/2020, 11:55:04 PM Got SIGINT, shutting down Bridge...
10/20/2020, 11:55:08 PM Loaded config.json with 0 accessories and 2 platforms.

I am not sure if I am missing something to run this, however I have not had this problem so far with Nest and iRobot, but that does not mean anything.  Node version 12.19.0 and Hoobs 3.2.7 on the latest mac OS.

I restarted Hoobs last night, did a clean install and received the same error.  I cleaned that up, rebooted, reinstalled w/ reboot and the bridge still was killed each time.  Let me me know if you need more of the log file as I am a bit new to these parts 👍

**Comment by balansse** [comment]
Could you please send the example of your config.json?

**Comment by balansse** [comment]
try installing the npm package react-native-securerandom manually:

npm install react-native --save
npm install react-native-web --save

or

sudo npm install react-native --save
sudo npm install react-native-web --save

I wonder why these install issues only happen on the HOOBS environment.

**Comment by jpop77** [comment]
Here you go, again I am a 101 moving on a 201 with this stuff:

{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "xx",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "xxx"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "xxx",
        "username": "xxx"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-nest"
    ],
    "accessories": [],
    "platforms": [
        {
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}

I removed some basic info and also the google auto for Nest.  Let me know if this is the file you need.  I think I am missing something and can try to install w/o Hoobs.  Let me know if you see something in there that I am missing?

**Comment by jpop77** [comment]
Ran those commands suggested above with a manual install.  I am still getting failures when trying to install with each option, global/sudo or not.  Here is what I am seeing when trying to install these pieces:

Here is what the terminal is saying:

Password:
npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
/usr/local/bin/react-native -> /usr/local/lib/node_modules/react-native/cli.js

> fsevents@1.2.13 install /usr/local/lib/node_modules/react-native/node_modules/fsevents
> node install.js

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/var/root/Library/Caches/node-gyp/12.19.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/react-native/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/react-native/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/react-native/node_modules/fsevents
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> core-js@2.6.11 postinstall /usr/local/lib/node_modules/react-native/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN react-native@0.63.3 requires a peer of react@16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN use-subscription@1.5.0 requires a peer of react@^17.0.0 but none is installed. You must install peer dependencies yourself.

+ react-native@0.63.3
added 741 packages from 412 contributors in 38.515s
bash-3.2$

**Comment by balansse** [comment]
Now try installing react package, looks like it is required as well

**Comment by closeshave2** [comment]
Still no luck after installing react, react-native and react-native-web.

**Comment by balansse** [comment]
Thanks everyone for the help! I'll have to experiment with HOOBS instance myself then. I'll update this issue as soon as I know what causes this.

**Comment by closeshave2** [comment]
I believe this must be a problem with HOOBS.  They've release v3.2.8 which they claim is supposed to fix the problem.  Unfortunately, for me, it just made it worse.  Just wanted to let you know...

**Comment by jpop77** [comment]
Just some color on my install, I installed the plugin yesterday and received the posted errors above.  I removed everything and updated Hoobs this morning and It failed again with the same errors as above around lacking requirements that need to be installed.  I also reinstalled react both with Sudo and adding the -g flag and it did not change the output.  I hope this helps, excited to use this plugin!

**Comment by closeshave2** [comment]
I updated to HOOBS to v3.2.8 and then uninstalled this plugin.  After reinstalling the plugin everything appears to be working correctly!

**Comment by jpop77** [comment]
I received the same error on 3.2.8 when it failed, did you happen to do anything else to make it a 'cleaner' reinstall that maybe I missed?  I removed the plugin, upgraded the server and rebooted after.  Once it was back up, confirmed that the correct packages were installed and then I reinstalled the plugin and it failed.  I did install Nest and iRobot and both worked however I am not sure if they required the same dependences as this package would require.  I can confirm that hoobs 3.2.7 and 3.2.8 both did not work under any method I have.

**Comment by closeshave2** [comment]
I did have to delete the cachedAccessories file after I deleted the Vivint plugin. Then I reinstalled the plugin, reconfigured it and rebooted. Everything seems to be working properly!

**Comment by jpop77** [comment]
Did you have this plugin working before or was this a new install for you?  I am formatting my server (mac OS) to run a fresh install of everything just in case.  I had tested about 8 other plugins first without any issues on various devices, however most of those plugins were not digging as deep and maybe required less dependences.  Even with modification on the config file on the latest HOOBS was failing as if the version never changed.   Thank you SO much @balansse for being responsive and trying to help a well informed rookie with this stuff.

**Comment by closeshave2** [comment]
I’m running on raspbian and I had this plugin working fine in v3.2.6 of HOOBS. This plugging stopped working this morning when I updated HOOBS to 3.2.7. I updated again this afternoon to 3.2.8 and reinstalled this plugin and now everything is working for me.

**Comment by balansse** [comment]
Please let me know if this issue is still happening after all the updates

**Comment by jpop77** [comment]
I do have this now up and running, I had to update my HOOBS to the latest edition.  Adding the camera logs helped a lot as well.

The only remaining problem I have is that both cameras use RTSP via FFMPEG and while now can see the feeds, when I go live with them on homekit they always time out.  What is odd is that when I open the steam on VLC it works great with no freeze or downtime.  However something keeps happing when I render this via homekit after following the exact config for the cameras.  Let me know if this is something you have heard about before.

**Comment by balansse** [comment]
> I do have this now up and running, I had to update my HOOBS to the latest edition. Adding the camera logs helped a lot as well.
> 
> The only remaining problem I have is that both cameras use RTSP via FFMPEG and while now can see the feeds, when I go live with them on homekit they always time out. What is odd is that when I open the steam on VLC it works great with no freeze or downtime. However something keeps happing when I render this via homekit after following the exact config for the cameras. Let me know if this is something you have heard about before.

I'm glad you don't have issues with HOOBS anymore!
Regarding the camera bug, please submit an issue to the [homebridge-camera-ffmpeg](https://github.com/Sunoo/homebridge-camera-ffmpeg/issues) repo as this is managed entirely by that plugin.
