### ISSUE TITLE
Error while bootstrapping accessories: Cannot read property PanelID...

### ISSUE THREAD

**Issue by jgwatkins** [balansse/homebridge-vivint#13]
I keep getting this error message on my Homebridge logs:

"**_Error while bootstrapping accessories: TypeError: Cannot read property 'PanelId' of undefined
    at Function.VivintApiModule.VivintApi.login (/usr/lib/node_modules/@balansse/homebridge-vivint/lib/vivint_api.js:160:47)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)_**"

I've tried the following:
- Restarted the whole system, and the Homebridge server.
- Verified my Vivint login.

Conditions:
- brand new install of homebridge on Raspberry Pi 3
- nodejs v12.19.0
- vivint panel model is the 'Go Control'

**Comment by balansse** [comment]
Wow this is unusual. Could you provide your config file?

**Comment by jgwatkins** [comment]
Here's the config.json file and the logs. I was wondering if the panel is an unsupported model.  
It is a vivint panel, but its one of the older ones. 
It's the 'Go Control' panel seen here: [https://support.vivint.com/s/article/Panel-User-Manuals]

Also my login credentials are correct in the config.json file and I have verified they do authenticate on vivint.com and at alarm.com.

**Here's the config file:**
[config-json.txt](https://github.com/balansse/homebridge-vivint/files/5449881/config-json.txt)

**Here's the homebridge log:**
[homebridgelog.txt](https://github.com/balansse/homebridge-vivint/files/5449840/homebridgelog.txt)

**Comment by balansse** [comment]
Oh, I'm afraid older panels are not supported by the Vivint API I am using. Good news - you can try using Alarm.com Homebridge plugin and see if it works:
https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com

**Comment by jgwatkins** [comment]
> Oh, I'm afraid older panels are not supported by the Vivint API I am using. Good news - you can try using Alarm.com Homebridge plugin and see if it works:
> https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com

That worked. Thank you, sir.
