### ISSUE TITLE
Panel disarms and rearms at 1am every day

### ISSUE THREAD

**Issue by sonatinas** [balansse/homebridge-vivint#14]
Hello,

I can't find in the logs why my panel disarms and rearms at 1am every day. It's not a setting on my actual panel. It appears to be the behavior after installing the plug in since my panel logs say it's a web login that is doing it. I have a HomeKit routine that puts it in armed(home mode) on a certain scene.

**Comment by balansse** [comment]
Could you describe your routine in more detail? Is it configured at the same time as this happening? 
Do you receive a HomeKit notification about a disarm/arm? Where do you see these events happening?

**Comment by sonatinas** [comment]
Hello,

I think I overlooked something after reading your comment. I have the same routine running every day at 1am(just in case I forgot or whatever) so when it runs again and the state hasn't changed it disarms and rearms. I'll disable the 1am routine to be sure but i think that's it. So, it seems while armed if another routine/scene has the same arming behavior it will disarm and rearm right then. I should have seen my other automations first but I forgot about that one. Sorry about that.
