### ISSUE TITLE
Homebridge 1.3.x breaks plugin

### ISSUE THREAD

**Issue by aacentric** [balansse/homebridge-vivint#20]
Homebridge 1.3.0 official was released and after update the plugin breaks.  Noticed this with the 1.3.x beta releases as well.  Rolled back to Homebridge 1.2.5 and the Vivint plugin works just fine again.

Seems to be the door locks, if I'm reading the logs correctly?

"[@balansse/homebridge-vivint] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Target State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info."

Please let me know if I can provide any more information or error logs. Thank you!

**Comment by keith760** [comment]
Having the same issue... Anyone else? Can't roll back to previous Homebridge version...

**Comment by rickypullan** [comment]
Having the same issue as well with the exact same errors showing in the logs. Also not able to roll back to a previous Homebridge build.

**Comment by balansse** [comment]
Wow, 1.3.0 is finally here! Thanks for the feedback about the errors, looks like there was more breaking changes than I expected! I am currently working on a big update, but will make a hotfix release as soon as possible.

**Comment by Vatosteve** [comment]
I am seeing issues with the door locks reporting errors as well. Everything else seems to be working ok so far, but the door locks do not.

I also noticed errors about the plugin being slow and I now configured it to be in a child bridge.

**Comment by balansse** [comment]
Please check out the latest 1.4.3 hotfix - I wasn't able to see any issues with 1.3.0 on my setup anymore.

**Comment by aacentric** [comment]
Tested out with my setup, no issues with the 1.4.3 hotfix and HB 1.3.0. Thank you, amazing work!

**Comment by Vatosteve** [comment]
Works great, thank you for such a quick update!
