### ISSUE TITLE
Live View Wont Load (HOOBS)

### ISSUE THREAD

**Issue by CaliberGSD** [balansse/homebridge-vivint#23]
I am having an issue where the Snapshot on HK is there but the cameras will never load live view. I am using HOOBS and very new to this. I am getting the following below when I run a live view

3/15/2021, 3:54:49 PM (node:3470) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'address' of undefined
3/15/2021, 3:54:49 PM at RTPStreamManagement.generateSetupEndpointResponse (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/camera/RTPStreamManagement.js:675:98)
3/15/2021, 3:54:49 PM at /usr/src/hoobs/node_modules/hap-nodejs/dist/lib/camera/RTPStreamManagement.js:644:27
3/15/2021, 3:54:49 PM at /usr/src/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:15:25
3/15/2021, 3:54:49 PM at Camera.prepareStream (/hoobs/node_modules/@balansse/homebridge-vivint/lib/accessories/camera.js:276:3)
3/15/2021, 3:54:49 PM at runMicrotasks (<anonymous>)
3/15/2021, 3:54:49 PM at processTicksAndRejections (internal/process/task_queues.js:97:5)
3/15/2021, 3:54:49 PM (node:3470) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by balansse** [comment]
What version of Homebridge your HOOBS instance is running? 

If you can, please run it in DEBUG mode and send me the complete log file from the moment it starts to the moment you run the liveview and see an error.

**Comment by CaliberGSD** [comment]
Good call. I was on HOOBS 3.3.2. Sorry about that. Upgraded and they load just fine now.
