### ISSUE TITLE
Doorbell functionality missing

### ISSUE THREAD

**Issue by ripple7511** [balansse/homebridge-vivint#26]
The added camera functionality is awesome, thanks for all of your work on this! 
However it looks like the cameras don't support the doorbell functionality, and the automation port is also missing. I'm not getting any doorbell notifications at all anymore.

**Comment by balansse** [comment]
The cameras and doorbell functionality is now a part of the plugin and does not require homebridge-camera-ffmpeg plugin anymore, so automation port is not used anymore. Please remove the camera-ffmpeg plugin and configure the native doorbell device that should appear after the upgrade.
