### ISSUE TITLE
Camera configuration missing

### ISSUE THREAD

**Issue by ripple7511** [balansse/homebridge-vivint#27]
With the newest updates, it looks like I'm no longer getting the camera configuration dumped into the console. Is this expected behavior?

**Comment by johnyoungberg** [comment]
The camera functionality is now included in this plugin so it is no longer necessary to output the configuration and copy it into another plugin.

**Comment by balansse** [comment]
The camera information can still be displayed in logs if Homebridge is running in DEBUG mode
