### ISSUE TITLE
Target Door State / Illegal value

### ISSUE THREAD

**Issue by snydema1** [balansse/homebridge-vivint#30]
good afternoon.  I just started seeing some of these errors in my log.  I went ahead and re-started homebridge and even rebooted my Mac mini.

[@balansse/homebridge-vivint] This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1. See https://git.io/JtMGR for more info.

not sure if it's actually causing a problem - everything seems to be working ok.  just figured I'd report in case you wanted to know.  thanks!

**Comment by ethanbrown3** [comment]
I'm seeing this a lot as well. My garage door opener can be finicky to get to close.
