### ISSUE TITLE
Cameras on Apple TV

### ISSUE THREAD

**Issue by wrathful77** [balansse/homebridge-vivint#33]
Love what you have done! My Vivint cameras work great on iPad and iPhone, but only show up as “no response” on my Apple TV. I think this is because they are not HomeKit certified… is there any way around this?

**Comment by ethanbrown3** [comment]
Strange, my cameras show on my Apple TV gen 5 fine.  What generation Apple TV do you have. What version of tvOS is it running?

**Comment by wrathful77** [comment]
Apple TV 4K model A1842 running tvOS 14.6. Wonder what I’m doing wrong then any ideas? I’ve tried logging out of iCloud and back in and everything else I could think of  and still get no response on Apple TV. While it works fine on iPad.

**Comment by wrathful77** [comment]
Figured it out basically I had my Apple TV plugged into a different network… Thanks for the assistance! Completely loving this, great work!!! Now I want more cameras.
