### ISSUE TITLE
No devices showing up on HomeKit app

### ISSUE THREAD

**Issue by jcdelacruz23** [balansse/homebridge-vivint#39]
After installing the plugin there were no vivint acceries that showed up on my HomeKit app and or on hoobs local.  Please help

**Comment by balansse** [comment]
Just pushed the 1.6.0 update that resolves the issue

**Comment by jcdelacruz23** [comment]
Just installed the new 1.6.0 update.  And my Vivint Devices still not showing up my hoobs accessory dashboard and HomeKit App.
