### ISSUE TITLE
Disarming alarm takes 30+ seconds to update HomeKit status, even though alarm actually disarms instantly

### ISSUE THREAD

**Issue by michaelyork** [balansse/homebridge-vivint#4]
Let me know if I can provide any debug info to assist!

**Comment by balansse** [comment]
Thank you for the feedback, I'm looking into it now!

**Comment by balansse** [comment]
Fixed in v0.0.13

**Comment by michaelyork** [comment]
Worked like a charm! Thank you @balansse. A coffee is on its way :)
