### ISSUE TITLE
Empty name prevented devices from being added

### ISSUE THREAD

**Issue by zackman0010** [balansse/homebridge-vivint#41]
After fixing the www. issue described in #37, I was greeted with a new error message.

[9/8/2021, 09:09:39] [Vivint] Error while bootstrapping accessories: AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:400:11)
    at new PlatformAccessory (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at Function.createDeviceAccessory (/usr/lib/node_modules/@balansse/homebridge-vivint/lib/device_set.js:147:23)
    at /usr/lib/node_modules/@balansse/homebridge-vivint/index.js:55:50
    at Array.map (<anonymous>)
    at /usr/lib/node_modules/@balansse/homebridge-vivint/index.js:55:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: '',
  expected: true,
  operator: '=='
}

After a bit of investigation, I found that it was the Nest Thermostat. The VivInt update had wiped the Name field, it was showing blank in the app. I had to remove and readd the thermostat to my VivInt account to let it regain its name. However, this one error with the thermostat prevented all other devices being registered by the VivInt plugin. The error message also made it very unclear which device was at fault. Maybe this error could be caught to provide better info?

**Comment by balansse** [comment]
@jgrimard I see you reverted the commit fixing this issue - can you tell me more about the reason?

**Comment by jgrimard** [comment]
@balansse I have no way of testing it myself.  I only have a base Vivint alarm system with sensors and a couple of zwave outlets linked to it.  I was going to have @zackman0010 test it but he got it working by reconnecting the thermostat to his alarm panel.   So I didn't want to make any changes without testing first.

**Comment by zackman0010** [comment]
The name came across as empty string `""` rather than `null`, so I don't think the change that was in the PR would have worked. It's been a long time since I worked with JavaScript, but I'm pretty sure `a || b` only uses `b` if `a` is `null`.

**Comment by jgrimard** [comment]
Hi @zackman0010 
It would work the same if it was and empty string or null.  

From: https://stackoverflow.com/questions/2100758/javascript-or-variable-assignment-explanation

The following values are considered falsy in JavaScript.
false
null
"" (empty string)
0
Nan
undefined

**Comment by zackman0010** [comment]
Then your change most likely would have worked. The only thing wrong with the response was that name was empty, and supplying a default value would have fixed that.

**Comment by jgrimard** [comment]
I don't think that code would have fixed the issue.  I just did a little testing and found that changing that line in device.js doesn't appear to do anything visible.  

I tried changing it to this, to simulate an empty string coming in:
```
        this.name = accessory.context.name
        this.name = ""
        log.info("name = " + this.name)
```
I got the below output in my logs and my accessories will still all named correctly.  I even cleared the accessory cache.  No crash at all.
```
[9/20/2021, 3:43:54 PM] [Vivint] Removing 0 accessories
[9/20/2021, 3:43:54 PM] [Vivint] Adding 3 accessories
[9/20/2021, 3:43:54 PM] [Vivint] name = 
[9/20/2021, 3:43:54 PM] [Vivint] name = 
[9/20/2021, 3:43:54 PM] [Vivint] name = 
```

So it looks like the crash is coming from somewhere else.

**Comment by NicoCanada** [comment]
Hello there,
I run into this issue and I found it is related to my Nest Thermostat connected to Vivint.
Since I am new to this project, I don't know how everything works together.
Here is the code in /usr/lib/node_modules/@balansse/homebridge-vivint/lib/device_set.js 
```  
...
if (splittedName.length > 1) {
          model = splittedName[1].toUpperCase()
        }
      }
      log.info(data) // log data 
      let accessory = new PlatformAccessory(
        data.Name + '1', // dirty fix
        uuid.generate("Vivint:" + data.Id + ":" + serial),
        category)
```
I used log.info(data) at line 144 and check what is before the error.
The follow was from the log.
```
...  },
  Online: true,
  Features: { Features_HVAC_AWAY_SETBACK: true, Features_HVAC_SCHEDULES: true },
  Name: '',
  Type: 'thermostat_device',
  WeekdayHeatSchedule: [
    {
```

I hope the information can help you a bit. 
Thanks for the wonderful work!
