### ISSUE TITLE
Adding HKSV Support

### ISSUE THREAD

**Issue by sundar2012** [balansse/homebridge-vivint#42]
Hi, any chance you can integrate with the approach here:

homebridge/HAP-NodeJS#904

https://github.com/koush/scrypted

to add HKSV to this plugin?

**Comment by iRayanKhan** [comment]
> Hi, any chance you can integrate with the approach here:
> 
> 
> 
> homebridge/HAP-NodeJS#904
> 
> 
> 
> https://github.com/koush/scrypted
> 
> 
> 
> to add HKSV to this plugin?

Stop going around every plugin asking for this to be added. HAP-NodeJS doesn't even support HKSV yet, so how can Homebridge, let alone plugins?

**Comment by sundar2012** [comment]
I posted this before I realized the faux pas.  new to GitHub. apologies.
