### ISSUE TITLE
Unable to link account using iPad web browser

### ISSUE THREAD

**Issue by mrfletch** [balansse/homebridge-vivint#53]
After tapping “Link Account” on my iPad I entered the username/password for my Vivint account. The “Login” button beneath the username and password text field does not appear to accept clicks/taps.

I’m accessing Hoobs in a Box via hoobs.local on my iPad. I’ve tried connecting using Safari, Chrome, and FireFox web browsers.

I’m headed to my desktop computer to try connecting there but I wanted to give you a friendly heads up that this doesn’t appear to be working on mobile web browsers.

Thanks for building this plugin and up-keeping it!

**Comment by mrfletch** [comment]
@jgrimard, now that the sidecar issue has been resolved should this empty response issue be tracked in this ticket?

Issue: https://github.com/hoobs-org/sidecars/issues/4#issuecomment-955653879

The login button is working, but the rest of the link flow isn’t.

**Comment by jgrimard** [comment]
I just tested the MFA login on both Homebridge and HOOBS and HOOBS is not logging in correctly.  Homebridge is working fine.  Please open a ticket on HOOBS and let them know.   I looked in the logs in HOOBS and don't see any errors of info being logged when attempting to login.  It just returns me back to the login and password screen.

https://github.com/hoobs-org/sidecars/issues/4
