### ISSUE TITLE
Link Account broken submission in HOOBS

### ISSUE THREAD

**Issue by veeo** [balansse/homebridge-vivint#54]
So excited about with plugin - thank you so much for maintaining this repo!
Looks like I'm unable to submit my login info via link account modal in HOOBS. "login" button is not working.
<img width="905" alt="Screen Shot 2021-10-30 at 5 48 35 PM" src="https://user-images.githubusercontent.com/506648/139559285-ec0ee985-9532-4100-b2fd-8df5bc262c53.png">

**Comment by jgrimard** [comment]
The HOOBS login user interface s maintained by HOOBS here:
https://github.com/hoobs-org/sidecars/issues/4

**Comment by jgrimard** [comment]
This has been fixed in HOOBS 4.1.13.  Please update your HOOBS to the latest version.  You might also need to re-install the homebridge-vivint plugin.  This issue can be closed.
