### ISSUE TITLE
Vivint not responding

### ISSUE THREAD

**Issue by 3aceskelsen** [balansse/homebridge-vivint#55]
Anyone else having issues with the plugin? My accessories are showing in homekit, but not responding. When I try to get a new refresh token it looks like it's throwing errors, which I don't understand enough to know if that's the issue.

**Comment by jgrimard** [comment]
@3aceskelsen 
I just tried refreshing my Vivint token in Homebridge and everything worked fine.  Can you post the errors you are getting?

**Comment by 3aceskelsen** [comment]
@jgrimar 
![Screen Shot 2021-11-28 at 9 32 38 AM](https://user-images.githubusercontent.com/3276331/143778072-788b15cc-46b5-4995-95e2-42603db525b7.png)
d

**Comment by 3aceskelsen** [comment]
@jgrimard
<img width="1352" alt="Screen Shot 2021-11-28 at 10 02 46 AM" src="https://user-images.githubusercontent.com/3276331/143778224-cbf0b03f-6e6d-43be-a0a1-c76159e5a4d9.png">
![Screen Shot 2021-11-28 at 9 30 03 AM](https://user-images.githubusercontent.com/3276331/143778233-057c2c22-f0eb-47c5-bbe8-7b3dc4cce214.png)

**Comment by jgrimard** [comment]
@3aceskelsen 
Ahh, you are using HOOBS, not Homebridge.  
You could try opening an issue over here on HOOBS.  This appears to be a HOOBS bug, since all is working well on Homebridge.
https://github.com/hoobs-org/sidecars/tree/main/hoobs-vivint-sidecar

**Comment by 3aceskelsen** [comment]
@jgrimard Thanks, I'll give that a shot.

**Comment by 3aceskelsen** [comment]
Just in case that other channel doesn't get a response I'll post my log here too.
@jgrimard does this give any more info that isn't neccessarily applicable to Hoobs
<img width="1341" alt="Screen Shot 2021-11-28 at 10 17 42 AM" src="https://user-images.githubusercontent.com/3276331/143778768-26ae892e-9660-4e33-8a51-1be26119798e.png">
?

**Comment by jgrimard** [comment]
@3aceskelsen  Please delete that last screen shot, it has your auth cookie which is used to log into your vivint account without the need for a name or password.

**Comment by 3aceskelsen** [comment]
> @3aceskelsen Please delete that last screen shot, it has your auth cookie which is used to log into your vivint account without the need for a name or password.

Thanks, missed that

**Comment by jgrimard** [comment]
@3aceskelsen 
Googling the error, it appears to be some sort of DNS issue.  Which DNS server do you use?
The DNS records seem to be fine, looking at: https://dnschecker.org/#A/www.vivintsky.com
From the search results it could be related to an incorrect setup in Docker?  Maybe try rebooting the HOOBS device to see if it refreshes itself?

**Comment by jgrimard** [comment]
Possibly the HOOBS device can not reach the internet.  You may want to verify that also.

**Comment by 3aceskelsen** [comment]
So after another suggestion I rebotted my home network and not just the raspberry pi and that seems to have worked.

**Comment by 3aceskelsen** [comment]
This issue has popped up again for me, but this time rebooting my home network doesn't seem to do anything. I've been working on this all evening, but can't figure out why I'm getting this error. Anyone have any ideas?

**Comment by 3aceskelsen** [comment]
Looks like the error was an update on the Hoobs system.
My Solution: https://support.hoobs.org/topics/connectivity/plugin-site-unavailable
