### ISSUE TITLE
Constant PubNub Errors

### ISSUE THREAD

**Issue by sharkannon** [balansse/homebridge-vivint#58]
I've been using the plugin for a long time, but lately been seeing 

```
[2/2/2022, 9:08:46 PM] [@balansse/homebridge-vivint] Could not connect to Pubnub, reconnecting...
[2/2/2022, 9:08:46 PM] [@balansse/homebridge-vivint] {
  error: true,
  operation: 'PNSubscribeOperation',
  errorData: Error: socket hang up
      at connResetException (node:internal/errors:691:14)
      at TLSSocket.socketOnEnd (node:_http_client:471:23)
      at TLSSocket.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    code: 'ECONNRESET',
    response: undefined
  },
  category: 'PNNetworkIssuesCategory'
}
[2/2/2022, 9:08:49 PM] [@balansse/homebridge-vivint] Reconnected to Pubnub
```

in the logs.  I have vivint running on a child bridge, just to keep it isolated from the rest of my infra.

Some details on my setup:
Hardware: Raspberry Pi 4 2GB (Ethernet Connected)
OS: Ubuntu 20.04
Homebridge: 1.4.0 running on Docker (oznu/homebridge:latest)
homebridge-vivint plugin: 1.6.0

Seems like this might be brought up again in the closed issue #19 , but figured I'd open a new ticket as that one was closed.

**Comment by sharkannon** [comment]
Just to note: My internet/network is extremely stable.  My Raspberry Pi's have been running on their own VLAN for a long time with no changes to the infrastructure (Also, vivint is the only one of my plugins that is complaining about connection issues).

**Comment by jcharnet** [comment]
I'm having the same issue, and I can also say my internet is pretty stable. Started happening after homebridge 1.4.0 was updated.

**Comment by jgrimard** [comment]
`errorData: Error: socket hang up`
I haven't seen that one before.  I just checked my logs.  Mine runs rock solid every day except 3am when my router / Fiber Gateway automatically reboots.
That error appears to be coming directly from NodeJS.  What version of Node are you running?
My Homebridge home screen shows: Node.js Version  v14.18.1

**Comment by jcharnet** [comment]
I’m on nodejs 16.13.2

**Comment by jgrimard** [comment]
Looks like @balansse encountered this same error a few years ago.  He may have some insight into what is going on.  I can't replicate the issue on my end.  
This was posted in the upstream branch:
https://github.com/timcharper/homebridge-vivint/issues/31#issue-639936216

**Comment by sharkannon** [comment]
I'm wondering if it's purely an upstream issue from Vivint or the like.  The issue seems to have gone away (it was happening for a couple of weeks).  I've done nothing on my end to resolve the issue.  I'll keep an eye on things and see what I can.. I'll leave this issue open for @jcharnet if he's still having issues.

**Comment by sharkannon** [comment]
My nodejs is also 16.13.2.

**Comment by jcharnet** [comment]
@sharkannon seems the issue did go away. And I also did not do anything on my end. Feel free to close this issue, and if it comes back we can revisit it.

Thanks,

**Comment by sharkannon** [comment]
Seems that this issue may be upstream with Vivint.. will close for now as it seems to have fixed itself.
