### ISSUE TITLE
Number of devices unhandled

### ISSUE THREAD

**Issue by nstuyvesant** [balansse/homebridge-vivint#6]
Really nice extension for HomeBridge!

Hey, I get a number of unhandled devices that are at least similar to ones already supported. Is there an easy way to configure the plugin to treat them like supported devices?

> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 49 Type: wireless_sensor EquipmentCode: 1267 Name: Basement - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 50 Type: sensor_group EquipmentCode: undefined Name: Basement - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 51 Type: wireless_sensor EquipmentCode: 708 Name: Basement - Smoke Detector - Heat
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 52 Type: wireless_sensor EquipmentCode: 556 Name: Basement - Smoke Detector - Freeze
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 53 Type: wireless_sensor EquipmentCode: 1267 Name: Hall 1 - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 54 Type: sensor_group EquipmentCode: undefined Name: Hall 1 - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 55 Type: wireless_sensor EquipmentCode: 708 Name: Hall 1 - Smoke Detector - Heat
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 56 Type: wireless_sensor EquipmentCode: 556 Name: Hall 1 - Smoke Detector - Freeze
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 57 Type: wireless_sensor EquipmentCode: 1266 Name: Hall 2 - CO Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 58 Type: wireless_sensor EquipmentCode: 1267 Name: Yoga Room - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 59 Type: sensor_group EquipmentCode: undefined Name: Yoga Room - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 60 Type: wireless_sensor EquipmentCode: 708 Name: Yoga Room - Smoke Detector - Heat
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 61 Type: wireless_sensor EquipmentCode: 556 Name: Yoga Room - Smoke Detector - Freeze
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 62 Type: wireless_sensor EquipmentCode: 1267 Name: Master Bedroom - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 63 Type: sensor_group EquipmentCode: undefined Name: Master Bedroom - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 64 Type: wireless_sensor EquipmentCode: 708 Name: Master Bedroom - Smoke Detector - Heat
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 65 Type: wireless_sensor EquipmentCode: 556 Name: Master Bedroom - Smoke Detector - Freeze
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 66 Type: wireless_sensor EquipmentCode: 1267 Name: Master Dressing - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 67 Type: sensor_group EquipmentCode: undefined Name: Master Dressing - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 68 Type: wireless_sensor EquipmentCode: 708 Name: Master Dressing - Smoke Detector - Heat
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 69 Type: wireless_sensor EquipmentCode: 556 Name: Master Dressing - Smoke Detector - Freeze
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 70 Type: wireless_sensor EquipmentCode: 1267 Name: 2nd Floor Guest Bedroom - Smoke Detector (Wired)
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 71 Type: sensor_group EquipmentCode: undefined Name: 2nd Floor Guest Bedroom - Smoke Detector (Wired)
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 72 Type: wireless_sensor EquipmentCode: 708 Name: 2nd Floor Guest Bedroom - Smoke Detector (Wired) - Heat
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 73 Type: wireless_sensor EquipmentCode: 556 Name: 2nd Floor Guest Bedroom - Smoke Detector (Wired) - Freeze
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 74 Type: wireless_sensor EquipmentCode: 1266 Name: Hall 3 - CO Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 75 Type: wireless_sensor EquipmentCode: 1267 Name: Hall 3 - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 76 Type: sensor_group EquipmentCode: undefined Name: Hall 3 - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 77 Type: wireless_sensor EquipmentCode: 708 Name: Hall 3 - Smoke Detector - Heat
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 78 Type: wireless_sensor EquipmentCode: 556 Name: Hall 3 - Smoke Detector - Freeze
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 83 Type: wireless_sensor EquipmentCode: 1267 Name: 3rd Floor Right Bedroom - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 84 Type: sensor_group EquipmentCode: undefined Name: 3rd Floor Right Bedroom - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 85 Type: wireless_sensor EquipmentCode: 708 Name: 3rd Floor Right Bedroom - Smoke Detector - Heat
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 86 Type: wireless_sensor EquipmentCode: 556 Name: 3rd Floor Right Bedroom - Smoke Detector - Freeze
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 87 Type: wireless_sensor EquipmentCode: 1267 Name: 3rd Floor Guest Room - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 88 Type: sensor_group EquipmentCode: undefined Name: 3rd Floor Guest Room - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 89 Type: wireless_sensor EquipmentCode: 708 Name: 3rd Floor Guest Room - Smoke Detector - Heat
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 90 Type: wireless_sensor EquipmentCode: 556 Name: 3rd Floor Guest Room - Smoke Detector - Freeze
> [9/8/2020, 9:47:23 PM] [Vivint] Ignored device ID: 94 Type: door_lock_device EquipmentCode: undefined Name: Back Door
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 97 Type: iot_device EquipmentCode: undefined Name: Hall Repeater
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 100 Type: iot_device EquipmentCode: undefined Name: Kitchen Repeater
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 103 Type: iot_service EquipmentCode: undefined Name: undefined
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 105 Type: scheduler_service EquipmentCode: undefined Name: undefined
> [9/8/2020, 9:47:23 PM] [Vivint] Ignored device ID: 135 Type: door_lock_device EquipmentCode: undefined Name: Front Door
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 145 Type: yofi_device EquipmentCode: undefined Name: AirBridge-145
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 146 Type: wireless_sensor EquipmentCode: 1267 Name: 3rd Floor Left Bedroom - Smoke Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 147 Type: wireless_sensor EquipmentCode: 708 Name: 3rd Floor Left Bedroom - Heat Detector
> [9/8/2020, 9:47:23 PM] [Vivint] Unhandled device ID: 149 Type: wireless_sensor EquipmentCode: 895 Name: Attic Heat Detector

**Comment by balansse** [comment]
Wow that is a lot of devices! 

Looking at their types I expect no difficulties adding support for them - all of the smoke/CO/heat/freeze detectors should be handled as a contact sensor. Thank you for the logs - I am now working on the next update and will include this request into it as well.

**Comment by nstuyvesant** [comment]
Fantastic - thank you!

**Comment by balansse** [comment]
Added in 1.0.0

**Comment by nstuyvesant** [comment]
Nice - had a long list of newly recognized devices to associate with rooms and rename tonight!

Still got a few errors...

> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:5 [Type]:energy_service [EquipmentCode]:undefined [Name]:undefined
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:12 [Type]:network_hosts_service [EquipmentCode]:undefined [Name]:undefined
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:13 [Type]:panel_diagnostics_service [EquipmentCode]:undefined [Name]:undefined
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:50 [Type]:sensor_group [EquipmentCode]:undefined [Name]:Basement - Smoke Detector
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:54 [Type]:sensor_group [EquipmentCode]:undefined [Name]:Hall 1 - Smoke Detector
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:59 [Type]:sensor_group [EquipmentCode]:undefined [Name]:Yoga Room - Smoke Detector
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:63 [Type]:sensor_group [EquipmentCode]:undefined [Name]:Master Bedroom - Smoke Detector
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:67 [Type]:sensor_group [EquipmentCode]:undefined [Name]:Master Dressing - Smoke Detector
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:71 [Type]:sensor_group [EquipmentCode]:undefined [Name]:2nd Floor Guest Bedroom - Smoke Detector (Wired)
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:76 [Type]:sensor_group [EquipmentCode]:undefined [Name]:Hall 3 - Smoke Detector
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:84 [Type]:sensor_group [EquipmentCode]:undefined [Name]:3rd Floor Right Bedroom - Smoke Detector
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:88 [Type]:sensor_group [EquipmentCode]:undefined [Name]:3rd Floor Guest Room - Smoke Detector
> [9/10/2020, 10:14:38 PM] [Vivint] Ignored device [ID]:94 [Type]:door_lock_device [EquipmentCode]:undefined [Name]:Back Door
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:97 [Type]:iot_device [EquipmentCode]:undefined [Name]:Hall Repeater
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:100 [Type]:iot_device [EquipmentCode]:undefined [Name]:Kitchen Repeater
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:103 [Type]:iot_service [EquipmentCode]:undefined [Name]:undefined
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:105 [Type]:scheduler_service [EquipmentCode]:undefined [Name]:undefined
> [9/10/2020, 10:14:38 PM] [Vivint] Ignored device [ID]:135 [Type]:door_lock_device [EquipmentCode]:undefined [Name]:Front Door
> [9/10/2020, 10:14:38 PM] [Vivint] Device not (yet) supported [ID]:145 [Type]:yofi_device [EquipmentCode]:undefined [Name]:AirBridge-145
> [9/10/2020, 10:14:38 PM] [Vivint] Removing 0 stale accessories
> [9/10/2020, 10:14:38 PM] [Vivint] Adding 0 new accessories

**Comment by balansse** [comment]
Glad to hear it worked! These are not errors - these devices have no HomeKit equivalent and are not useful.

**Comment by nstuyvesant** [comment]
The odd ones were the lines for the Smoke Detectors. These were correctly recognized as but they log as undefined here. The other ones like the Z-Wave Repeater don't really map to anything I could use as you pointed out.

**Comment by balansse** [comment]
They have type: sensor_group so I guess it is just a virtual device to group smoke/heat/freeze sensors together

**Comment by nstuyvesant** [comment]
That kind of makes sense as one physical Smoke/Heat/Freeze Detector now appears as three devices.
