### ISSUE TITLE
Random shutdowns and poor behavior with plugin

### ISSUE THREAD

**Issue by asander85** [balansse/homebridge-vivint#61]
This plugin is amazing when it is working, but more often than not I pull up my Home app on iphone or ipad and all my Vivint accessories failed to communicate. A restart to the plugin or the Homebridge itself fixes it for a while, but it riddled with errors in the log, mostly communication error it looks like. I have sequential 2000 Mbps fiber service here (down AND upload) and all is verified to be operational and setup correctly. 
My config is below (login details omitted) and I attached a notepad file with my logs here 
```
[ASANDER HOMEBRIDGE LOGS 4.29.22.txt](https://github.com/balansse/homebridge-vivint/files/8593113/ASANDER.HOMEBRIDGE.LOGS.4.29.22.txt)


{
    "bridge": {
        "name": "Homebridge 8E6C",
        "username": "0E:6B:EA:52:8E:6C",
        "port": 51120,
        "pin": "540-60-439",
        "advertiser": "ciao",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "dark-mode-cyan",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "refreshToken": "XXX",
            "apiLoginRefreshSecs": 600,
            "ignoreDeviceTypes": [
                "garage_door_device"
            ],
            "useExternalVideoStreams": true,
            "_bridge": {
                "username": "0E:39:78:88:83:12",
                "port": 58475
            },
            "platform": "Vivint"
        },
        {
            "email": "XXX.com",
            "password": "XXX",
            "name": "myQ",
            "platform": "myQ",
            "_bridge": {
                "username": "0E:86:39:1A:DB:E1",
                "port": 54876
            }
        },
        {
            "name": "B-Hyve",
            "email": "XXX.com",
            "password": "XXX",
            "locationAddress": "xxxx Stxxxgatx Mxxox xx",
            "defaultRuntime": 10,
            "runtimeSource": 2,
            "useIrrigationDisplay": true,
            "displayValveType": 1,
            "showIrrigation": true,
            "showBridge": false,
            "showFloodSensor": false,
            "showTempSensor": false,
            "showLimitsSensor": false,
            "showStandby": false,
            "showRunall": true,
            "showSchedules": true,
            "platform": "bhyve",
            "_bridge": {
                "username": "0E:43:5D:4A:88:9C",
                "port": 32562
            }
        }
    ]
}

```
THANKS!!!

**Comment by jgrimard** [comment]
Don't post your refresh token. Anyone can use it to control your alarm and even view your home address.

**Comment by asander85** [comment]
> Don't post your refresh token. Anyone can use it to control your alarm and even view your home address.

Edited, thanks for the heads up. I sortof figured those were one-time use only tokens and couldn't be used, but I guess there's really no reason for the dev or community to need to see that either.

**Comment by jgrimard** [comment]
> > Don't post your refresh token. Anyone can use it to control your alarm and even view your home address.
> 
> Edited, thanks for the heads up. I sortof figured those were one-time use only tokens and couldn't be used, but I guess there's really no reason for the dev or community to need to see that either.

Nope, the same token used every time the plugin connects to Vivint.  It only expires if not used for 6 months I believe. You can also manually expire it by changing your password I believe. I think it gives you the option of logging out all devices.

**Comment by balansse** [comment]
I just published a 1.6.1 release that should make it better. Please update and let me know!

**Comment by asander85** [comment]
I really thought it was better at first, but unfortunately no. I continue to have these errors even after the update. Also, I have lots of problems with the cameras. 8/10 times you click on a camera (I have 4). I will say I was excited to hear a doorbell notification on my HomePods after the update. 
I have heard of people using the Vivint plugin for everything but cameras and using cameraui and it adds two way communication functionality as well as HomeKit secure video and playback…but the setup looks WAY above my skill level.

**Comment by asander85** [comment]
[37m[03/05/2022, 17:56:38] ***@***.***/homebridge-vivint][39m [31mError refreshing login info: RequestError: Error: Client network socket disconnected before secure TLS connection was established[39m

[31m    at new RequestError ***@***.***/homebridge-vivint/node_modules/request-promise-core/lib/errors.js:14:15)[39m

[31m    at Request.plumbing.callback ***@***.***/homebridge-vivint/node_modules/request-promise-core/lib/plumbing.js:87:29)[39m

[31m    at Request.RP$callback [as _callback] ***@***.***/homebridge-vivint/node_modules/request-promise-core/lib/plumbing.js:46:31)[39m

[31m    at self.callback ***@***.***/homebridge-vivint/node_modules/request/request.js:185:22)[39m

[31m    at Request.emit (node:events:526:28)[39m

[31m    at Request.onRequestError ***@***.***/homebridge-vivint/node_modules/request/request.js:877:8)[39m

[31m    at ClientRequest.emit (node:events:526:28)[39m

[31m    at TLSSocket.socketErrorListener (node:_http_client:442:9)[39m

[31m    at TLSSocket.emit (node:events:526:28)[39m

[31m    at emitErrorNT (node:internal/streams/destroy:157:8) {[39m

[31m  cause: Error: Client network socket disconnected before secure TLS connection was established[39m

[31m      at connResetException (node:internal/errors:691:14)[39m

[31m      at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)[39m

[31m      at TLSSocket.emit (node:events:538:35)[39m

[31m      at endReadableNT (node:internal/streams/readable:1345:12)[39m

[31m      at processTicksAndRejections (node:internal/process/task_queues:83:21) {[39m

[31m    code: 'ECONNRESET',[39m

[31m    path: null,[39m

[31m    host: 'www.vivintsky.com',[39m

[31m    port: 443,[39m

[31m    localAddress: undefined[39m

[31m  },[39m

[31m  error: Error: Client network socket disconnected before secure TLS connection was established[39m

[31m      at connResetException (node:internal/errors:691:14)[39m

[31m      at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)[39m

[31m      at TLSSocket.emit (node:events:538:35)[39m

[31m      at endReadableNT (node:internal/streams/readable:1345:12)[39m

[31m      at processTicksAndRejections (node:internal/process/task_queues:83:21) {[39m

[31m    code: 'ECONNRESET',[39m

[31m    path: null,[39m

[31m    host: 'www.vivintsky.com',[39m

[31m    port: 443,[39m

[31m    localAddress: undefined[39m

[31m  },[39m

[31m  options: {[39m

[31m    url: 'https://www.vivintsky.com/api/panel-login/788756644500692',[39m

[31m    headers: {[39m

[31m      Cookie: 's=22cf969c-2a10-4178-a15c-fa6f050a2530',[39m

[31m      'Cache-Control': 'no-store'[39m

[31m    },[39m

[31m    callback: [Function: RP$callback],[39m

[31m    transform: undefined,[39m

[31m    simple: true,[39m

[31m    resolveWithFullResponse: false,[39m

[31m    transform2xxOnly: false[39m

[31m  },[39m

[31m  response: undefined[39m

[31m}[39m

[37m[03/05/2022, 18:26:38] ***@***.***/homebridge-vivint][39m [31mError refreshing login info: RequestError: Error: Client network socket disconnected before secure TLS connection was established[39m

[31m    at new RequestError ***@***.***/homebridge-vivint/node_modules/request-promise-core/lib/errors.js:14:15)[39m

[31m    at Request.plumbing.callback ***@***.***/homebridge-vivint/node_modules/request-promise-core/lib/plumbing.js:87:29)[39m

[31m    at Request.RP$callback [as _callback] ***@***.***/homebridge-vivint/node_modules/request-promise-core/lib/plumbing.js:46:31)[39m

[31m    at self.callback ***@***.***/homebridge-vivint/node_modules/request/request.js:185:22)[39m

[31m    at Request.emit (node:events:526:28)[39m

[31m    at Request.onRequestError ***@***.***/homebridge-vivint/node_modules/request/request.js:877:8)[39m

[31m    at ClientRequest.emit (node:events:526:28)[39m

[31m    at TLSSocket.socketErrorListener (node:_http_client:442:9)[39m

[31m    at TLSSocket.emit (node:events:526:28)[39m

[31m    at emitErrorNT (node:internal/streams/destroy:157:8) {[39m

[31m  cause: Error: Client network socket disconnected before secure TLS connection was established[39m

[31m      at connResetException (node:internal/errors:691:14)[39m

[31m      at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)[39m

[31m      at TLSSocket.emit (node:events:538:35)[39m

[31m      at endReadableNT (node:internal/streams/readable:1345:12)[39m

[31m      at processTicksAndRejections (node:internal/process/task_queues:83:21) {[39m

[31m    code: 'ECONNRESET',[39m

[31m    path: null,[39m

[31m    host: 'www.vivintsky.com',[39m

[31m    port: 443,[39m

[31m    localAddress: undefined[39m

[31m  },[39m

[31m  error: Error: Client network socket disconnected before secure TLS connection was established[39m

[31m      at connResetException (node:internal/errors:691:14)[39m

[31m      at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)[39m

[31m      at TLSSocket.emit (node:events:538:35)[39m

[31m      at endReadableNT (node:internal/streams/readable:1345:12)[39m

[31m      at processTicksAndRejections (node:internal/process/task_queues:83:21) {[39m

[31m    code: 'ECONNRESET',[39m

[31m    path: null,[39m

[31m    host: 'www.vivintsky.com',[39m

[31m    port: 443,[39m

[31m    localAddress: undefined[39m

[31m  },[39m

[31m  options: {[39m

[31m    url: 'https://www.vivintsky.com/api/panel-login/788756644500692',[39m

[31m    headers: {[39m

[31m      Cookie: 's=22cf969c-2a10-4178-a15c-fa6f050a2530',[39m

[31m      'Cache-Control': 'no-store'[39m

[31m    },[39m

[31m    callback: [Function: RP$callback],[39m

[31m    transform: undefined,[39m

[31m    simple: true,[39m

[31m    resolveWithFullResponse: false,[39m

[31m    transform2xxOnly: false[39m

[31m  },[39m

[31m  response: undefined[39m

[31m}[39m

**Comment by balansse** [comment]
This looks like a network connection error - did you try rebooting your Homebridge instance?

**Comment by balansse** [comment]
Also, "apiLoginRefreshSecs": 600 looks way too often, could you try increasing it to 1800?

**Comment by asander85** [comment]
First, I want to say thank you for working so hard on these, it's awesome. I've changed a few things since I posted this:
API login was changed to 1780. Also stopped using ciao in favor of Bonjour. Got rid of Alexa, Orbit, and Samsung plugins, left with myQ, Vivint, and Camera.ui (camera.ui takes up a ton of processing power from the pi)
I had a feeling my woes were due to network traffic, but I don't really understand how to resolve that. I have fiber 2Gbps upload and 2Gbps download speed (2000Mbps) and all my other devices and plugins are communicating ok. 
Is there anyway we could schedule a remote session (if I compensate of course) when I get home from a work trip next week?

**Comment by balansse** [comment]
Sure we can do that - shoot me an email at balansse@gmail.com

**Comment by balansse** [comment]
@asander85 do you still experience issues?

**Comment by asander85** [comment]
@balansse many apologies, sir that I didn't connect back with you. I ended up moving some wired switches around and it seems to have improved things. however, I am still getting some odd errors. The most recent one was just a few minutes ago. Any idea what this error in the log represents?

`[7/1/2022, 6:17:43 AM] [@balansse/homebridge-vivint] Error getting system info: RequestError: Error: read ETIMEDOUT
    at new RequestError (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.onRequestError (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8) {
  cause: Error: read ETIMEDOUT
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'read'
  },
  error: Error: read ETIMEDOUT
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'read'
  },
  options: {
    url: 'https://www.vivintsky.com/api/systems/788756644500692',
    headers: {
      Cookie: 's=97023a9f-0eb0-4143-b63b-e1ed17a7fd86',
      'Cache-Control': 'no-store'
    },
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}'

I am currently running homebridge installed via docker on a RP3B+ booting from an external 128GB NVME M.2 SSD (only other thing on the PI is the Raspian OS). When it comes in (HOPEFULLY next week) I'll be either moving everything over to a RP4 w/ 8GB of RAM or I'll just start over from scratch on the new Pi.

**Comment by asander85** [comment]
@ jgrimard thanks. I never know what should and should not be included when I post these. Like, I don’t want to omit vital info for duplication but also don’t really Intend to be advertising my logins for the whole world to see. Honestly I guess I assumed that anyone here is upstanding but that’s not a great assumption I know.Sent from my iPhoneOn Jul 1, 2022, at 9:07 AM, jgrimard ***@***.***> wrote:﻿
@asander85 Please don't post your "cookie". Anyone can use that to log into your account and control your system.
@balansse Maybe we should remove printing the cookie value to the log to prevent this from happening.  Or maybe add some code so it only prints when debugging is turned on.
