### ISSUE TITLE
Current Heating Cooling State received undefined but expected finite number

### ISSUE THREAD

**Issue by myleftnuthurts** [balansse/homebridge-vivint#62]
Pretty new to this plugin and reporting the following status:

[@balansse/homebridge-vivint] This plugin generated a warning from the characteristic 'Current Heating Cooling State': characteristic value expected valid finite number and received "undefined" (undefined).

**Comment by asander85** [comment]
Mine has done that constantly since install, I'd like a fix for this as well.
