### ISSUE TITLE
Support for camera drive and possible water sensor bug? 

### ISSUE THREAD

**Issue by suedeyoung** [balansse/homebridge-vivint#67]
Hey there! 

First, I love the plugin! I recently started diving a bit more headfirst into the smart home stuff and it's been suuuppperrr nice to have vivint in homekit for once. 

I did notice this in the logs and was wondering if there was any plans on supporting this? This would let us see the recorded footage possibly? (not sure if that's a fully locked system or something that we can pull with this)

`[6/17/2022, 3:26:07 AM] [Vivint] Device not (yet) supported [ID]:72 [Type]:lgit_poe_wifi_device [EquipmentCode]:undefined [Name]:Driveway-Bridge`

For the water sensor, I am seeing this in the logs when I restarted homebridge: 
`[6/17/2022, 3:26:07 AM] [Vivint] Device not (yet) supported [ID]:31 [Type]:wireless_sensor [EquipmentCode]:1264 [Name]:Laundry Water Sensor`

However, when checking homekit and the accessories tab I am seeing the laundry sensor. Not sure if that was a bug or something else. 

Thanks again for the awesome plugin!

**Comment by balansse** [comment]
> [6/17/2022, 3:26:07 AM] [Vivint] Device not (yet) supported [ID]:72 [Type]:lgit_poe_wifi_device [EquipmentCode]:undefined [Name]:Driveway-Bridge
This device is completely unusable in HomeKit unfortunately

> [6/17/2022, 3:26:07 AM] [Vivint] Device not (yet) supported [ID]:31 [Type]:wireless_sensor [EquipmentCode]:1264 [Name]:Laundry Water Sensor
Thank you for the logs! I will add the support for this device in the next update
