### ISSUE TITLE
Smoke Detectors & Glass break sensors

### ISSUE THREAD

**Issue by vcdx71** [balansse/homebridge-vivint#7]
I just moved to your version of the plugin since it’s verified and you support more object types.

That said all my smoke and glass break sensors came into home as contact sensors. HomeKit natively supports smoke detectors, is there any way to make these show as that device type?

**Comment by balansse** [comment]
I'll see what can be done - even though it is still an on/off type device, if it can be exposed to HomeKit as a smoke detector device it would definitely be a cleaner approach. Is glass break sensor also natively supported by HomeKit?

**Comment by vcdx71** [comment]
Awesome.

No unfortunately glass break isn’t native, I shouldn’t have mentioned that one.. I had a Honeywell lyric before I moved and glass break showed up as a contact sensor as well.

**Comment by balansse** [comment]
Added support for smoke sensors and carbon monoxide sensors in 1.1.0
