### ISSUE TITLE
Showcameraconfig

### ISSUE THREAD

**Issue by j0np** [balansse/homebridge-vivint#77]
Wondering if we can re-add the showcameraconfig option back as the debug log shows username and password for the camera that doesnt work anymore when trying to use it with ffmpeg.

**Comment by balansse** [comment]
Yeah I was thinking about  that - will add it in the next update

**Comment by j0np** [comment]
Awesome thank you sooo much!! Would be huge help

**Comment by j0np** [comment]
Any update on this request?
