### ISSUE TITLE
Separate Doorbell Button Press from Camera Accessory

### ISSUE THREAD

**Issue by asander85** [balansse/homebridge-vivint#78]
I'm wondering if it would be possible to separate the doorbell button press and the doorbell camera. 

In Homebridge, I am currently disabling cameras on the Vivint plugin in favor of having them stream using the camera.ui plugin. This provides all 5 of my cameras HKSV functionality, but removes the doorbell press notification. I'm sure there is some way of triggering the doorbell press using MQTT, but I wouldn't know where to start to find that information.

If I could keep the camera feeds disabled, but just enable to doorbell button in Homebridge that would be a HOME RUN!!! 

A GRAND SLAM would be if the Vivint cameras could be HKSV compatible...but I'm sure that is quite the enhancement over the current functionality.

**Comment by balansse** [comment]
That is an interesting idea. Although I plan to add HKSV support to the plugin someday, this might be a nice workaround in the meantime.

PS. Thank you for being a sponsor and supporting my work! I already ordered a new doorbell camera pro so I can check its compatibility and add it to the list of supported devices.

**Comment by asander85** [comment]
You are more than welcome!!! The Vivint plugin is the basis for my entire homekit environment, and I SUPER appreciate all the hard work you have CLEARLY put into this. Hard work and good performance deserve accolades...and it's hard to pay a mortgage with verbal "Thank You's" lol. 

I'm trying a workaround today where I have the camera feeds coming to Homekit from both the Vivint Plugin AND camera.ui. I then hide all the Vivint cameras from the "Home" view in the home app and turn off all notifications and status changes EXCEPT the doorbell notification. This works well for the iphone and ipads, but the camera view on my Apple TV's kindof sucks like this as I can't remove the duplicates. Performance wise I am getting the same response as I was before I was using camera.ui for cameras: the doorbell press notification only notifies my apple homekit devices if I have refreshed the camera feeds within the last 30 seconds. Any longer than that and I don't seem to get notified. Is there a fix for that? Maybe some options to increase the snapshot refresh time to like 20 seconds or something? I'm running everything on an RPi4 w/ 8gb of RAM, homebridge (avahi protocol) sudo installed via terminal inside Raspberry Pi OS 64bit - internet is AT&T Fiber 2GB download 2GB upload verified, straight ethernet; so CPU usage shouldn't be an issue. 

On a somewhat un-related noted, I have been having big time reliability and connection issues with my Vivint Doorbell Camera Pro (2nd gen, DBC300 I think, I'm 99% sure these are hardware issues and not a problem with your plugin) and I am considering upgrading to either the new Vivint one or...abandoning Vvint on the doorbell in favor of a native HKSV solution. The more I think about it, the more I am realizing that the doorbell camera is the most valuable accessory I use (I work from home in the basement office, want our packages protected, etc., etc.) and it really should be the most reliable thing here.

Just thinking out loud...it all kindof depends on the user feedback from the newest Vivint camera. It sure looks nice in the online store tho!

**Comment by aacentric** [comment]
If it were possible to have the doorbell press event come through as a separate device or event that would be amazing - would really be great to capture the doorbell press separately to use for different services.
