### ISSUE TITLE
login window loads, hangs, then does nothing

### ISSUE THREAD

**Issue by skyleranelson** [balansse/homebridge-vivint#79]
When linking my account it acts like it's linking but then just stops and goes back to the login screen. I've tried just about everything from adding new bridges, reseting Vivint account login, rebooting, wifi on/off ... any other suggestions?

<img width="944" alt="CleanShot 2022-08-19 at 17 05 31@2x" src="https://user-images.githubusercontent.com/111613234/185713250-0203bbe7-4107-4cd1-870b-6d7b49041593.png">
<img width="887" alt="CleanShot 2022-08-19 at 17 05 19@2x" src="https://user-images.githubusercontent.com/111613234/185713252-0217c6d5-043a-4125-981b-40e78d6fcd03.png">

**Comment by jgrimard** [comment]
Are there any errors in the logs?  I just tried deleting my refresh token and logging in again and it worked fine for me.

**Comment by skyleranelson** [comment]
> Are there any errors in the logs? I just tried deleting my refresh token and logging in again and it worked fine for me.

Nothing. It's like it doesn't even see anything. I'm wondering if it's a network issue ... but all the other plugins are working.

**Comment by jgrimard** [comment]
Oh, are you using HOOBS?  It is probably a bug in HOOBS.  They wrote a "sidecar" to get this Homebridge plugin working in HOOBS.   I would try opening a ticket here:  https://github.com/hoobs-org/sidecars/tree/main/hoobs-vivint-sidecar

**Comment by skyleranelson** [comment]
Ah, thanks. I'll post there ... Assuming it's the same thing as https://plugins.hoobs.org/plugin/@balansse/homebridge-vivint A it over my head honestly.

**Comment by jgrimard** [comment]
If all else fails, you could use the command line utility I wrote to retrieve your refresh token then copy and paste it into the configuration.

From here: https://github.com/balansse/homebridge-vivint  About half way down the page.
HOOBS Users:
Unfortunately HOOBS doesn't support the Custom UI components created for Homebridge.

As a workaround, you can open a terminal in HOOBS and run the following commands, where "vivintbridge" is the name of the bridge but all lowercase and with no spaces:

cd /var/lib/hoobs/vivintbridge/node_modules/@balansse/homebridge-vivint
npm run mfa

**Comment by jgrimard** [comment]
if npm run mfa doesn't work then locate the file named vivint_mfa_cli.js  and use  `node vivint_mfa_cli.js`  to run it

**Comment by skyleranelson** [comment]
That would be amazing. Seems like I'm having the same issue when accessing the terminal, too. Enter login info and just spits me back to "login ...."

**Comment by jgrimard** [comment]
Sounds like something is really wrong with HOOBS if you can't get into the terminal.

**Comment by skyleranelson** [comment]
Not sure what the hell is going on. 
https://file.letsalloy.com/1b74pI

**Comment by skyleranelson** [comment]
might have to flash HOOBS and start over.

**Comment by jgrimard** [comment]
according to: https://support.hoobs.org/docs/60e6310b6c19a6a5ca8f5c5f
The terminal login is:
The login is hoobs
And the default password is hoobsadmin

**Comment by skyleranelson** [comment]
Sheesh. That worked! Got the refresh key. Running and added to HomeKit.  No devices visible... still looking around.

**Comment by jgrimard** [comment]
Make sure you restart HOOBS.

**Comment by skyleranelson** [comment]
yeah. tried restarting the specific bridge and rebooting the sys. still empty so far.

**Comment by jgrimard** [comment]
Any errors in the logs?

**Comment by skyleranelson** [comment]
nah, updating everything to see if that helps.

**Comment by skyleranelson** [comment]
yo - Got it! Couldn't have done it without you!

**Comment by jgrimard** [comment]
Great!  You can go ahead and close this issue.
