### ISSUE TITLE
Video stream error

### ISSUE THREAD

**Issue by 3aceskelsen** [balansse/homebridge-vivint#81]
Anyone know what this issue is? The link suggest it's an issue with the plug-in. Just started today. Additionally the Vivint devices are loading really slow compared to other plugins. 

![image](https://user-images.githubusercontent.com/3276331/190887505-474d0c8e-4ec8-4401-b0a8-f31871873aa3.jpeg)

**Comment by iJasonWade** [comment]
I just started having this same issue a day ago.

**Comment by 3aceskelsen** [comment]
A slightly different error. @balansse the error says this needs to be reported to the plugin dev.

<img width="1391" alt="Screen Shot 2022-10-06 at 8 07 35 AM" src="https://user-images.githubusercontent.com/3276331/194335617-1f34e9ae-f7fe-4a26-9553-14a29e3d656e.png">

**Comment by 3aceskelsen** [comment]
Seems like the issue might be with Hoobs. I switched to HomeBridge and everything is working great!
