### ISSUE TITLE
Trouble logging in

### ISSUE THREAD

**Issue by skyleranelson** [balansse/homebridge-vivint#94]
I install and login to authenticate but it just hangs. Using Hoobs and its own bridge. Manual configuration doesn't seem to work either. Any advice?

**Comment by jgrimard** [comment]
Can you post this in Hoobs?  Hoobs uses its own login screens.   Link below.
[https://github.com/hoobs-org/sidecars](https://github.com/hoobs-org/sidecars)

**Comment by skyleranelson** [comment]
> Can you post this in Hoobs? Hoobs uses its own login screens. Link below.
> https://github.com/hoobs-org/sidecars

yeah... bummer. I actually did already back in August.

**Comment by jgrimard** [comment]
> yeah... bummer. I actually did already back in August.

You could give your post a bump to see if they can work on it.  This repository is for regular Homebridge.  Hoobs is different and requires sidecars to get login screens to work.  I'm not sure exactly how they work.

**Comment by skyleranelson** [comment]
Closing issue here since this isn't homebridge related.
